name: Remanso
version: 0
main: com.github.remanso.Remanso
description: Manage land in single-kingdom Minecraft servers with this simple plugin!
author: magenta555
website: https://github.com/magenta555/Remanso
api-version: 1.21.4
commands:
  remanso:
    description: Display plugin information or use all Remanso commands!
    permission: remanso.remanso
    permission-message: You cannot use this command.
    usage: /remanso
  r:
    description: Display plugin information or use all Remanso commands!
    permission: remanso.r
    permission-message: You cannot use this command.
    usage: /r