name: Remanso
version: 0
main: com.github.remanso.Remanso
api-version: 1.21.4
author: magenta555
website: github.com/magenta555/remanso
commands:
  zonetool:
    description: Gives you a zoning tool.
    usage: /zonetool
    permission: remanso.zonetool
  zonecreate:
    description: Create a zone after using a zoning tool.
    usage: /zonecreate <name> <purpose>
    permission: remanso.zonecreate
  zonename:
    description: Change the name of the zone you're standing in.
    usage: /zonename <name>
    permission: remanso.zonename
  zonepurpose:
    description: Change the purpose of the zone you're standing in.
    usage: /zonepurpose <purpose>
    permission: remanso.zonepurpose
  zoneinfo:
    description: Get information about the zone you're standing in.
    usage: /zoneinfo
    permission: remanso.zoneinfo
  zonedelete:
    description: Delete the zone you're standing in.
    usage: /zonedelete
    permission: remanso.zonedelete
  zonemerge:
    description: Merge two zones after using a zoning tool.
    usage: /zonemerge
    permission: remanso.zonemerge
  zoneteleport:
    description: Teleport to a zone.
    usage: /zoneteleport <name>
    permission: remanso.zoneteleport
  zonesetteleport:
    description: Set the teleport location for the zone you're standing in.
    usage: /zonesetteleport
    permission: remanso.zonesetteleport